#!usr/bin/env bash
# this configures an Nginx server to listen on port 80.
# Also remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# This configures Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
