#!/usr/bin/env bash
#This creates file in /var/run/myscript.pid containing its PID
#Displays I hate the kill command when recieving a SIGTERM signal
#Deletes the file /var/run/myscript.pid and terminates itself when recieving a SIGQUIT or SIGTERM signal.

echo "$$" > /var/run/myscript.pid

termfunc()

{
  rm /var/run/myscript.pid
  exit
}


while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && termfunc' SIGTERM
  trap 'termfunc' SIGQUIT
done
