#!/usr/bin/env bash
# Script displays content of current directory in a list format
# Only displays part of name after first dash

mylist=$(ls)

for i in $mylist; do

  echo "$i" | cut -d '-' -f2

done
